// pages/_app.js
import React from 'react';
import App from 'next/app';
import "@/app/globals.css";
import TopBar from '@/components/TopBar';

export const metadata = {
    title: "Screenshot Toaster",
    description: "Generated by create next app",
};

function RootLayout({ children }) {
    return (
        <div className='h-screen w-screen overflow-hidden'>{children}</div>
    );
}


class MyApp extends App {
    render() {
        const { Component, pageProps } = this.props;
        return (
            <RootLayout> {/* RootLayout 컴포넌트로 감싸줍니다. */}
                <TopBar />
                <Component {...pageProps} />
            </RootLayout>
        );
    }
}

export default MyApp;
