import { Pretendard } from "next/font/google";
import "./globals.css";

const pretendard = Pretendard({
  preload: false,
  weight: ["100", "400", "700", "900"],
  variable: "--pretendard"
});

export const metadata = {
  title: "Screenshot Toaster",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="kr">
      <body className={cls(pretendard.className, 'overflow-hidden')}>
            {children}
      </body>
    </html>
  );
}
